name: Auto Comment
on:
  pull_request:
    paths:
      - 'train.py'
      - 'Giskard_test.py'
      - '.github/workflows/deployment.yml'
      - 'data.csv'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.

          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
            - if the file `deployed_model` is created, it means that the Giskard tests has passed, and a summary of them can be found in `deployed_model`.
            - if not, that means that the model issued from this PR is not deployed and it didn't pass Giskard's tests.
